#!/usr/bin/env bash
# 将本机薄包装安装到 ~/bin/openclaw-usage
set -euo pipefail

FORCE=0
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    -h|--help)
      cat <<'EOF'
Usage: ./scripts/install-local-launcher.sh [--force]

Installs a thin wrapper at ~/bin/openclaw-usage that forwards to this
repository's scripts/openclaw-usage-cli.js via an absolute path.

  --force   Replace an existing ~/bin/openclaw-usage even if it was not
            generated by this installer.
EOF
      exit 0
      ;;
    *)
      echo "Unknown argument: $arg" >&2
      echo "Use --help for usage." >&2
      exit 1
      ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CLI_PATH="$REPO_ROOT/scripts/openclaw-usage-cli.js"
TARGET_DIR="${HOME}/bin"
TARGET="$TARGET_DIR/openclaw-usage"
MARKER="# openclaw-usage-local-launcher"

if ! command -v node >/dev/null 2>&1; then
  echo "Error: node is required but not found in PATH." >&2
  exit 1
fi

if ! command -v npm >/dev/null 2>&1; then
  echo "Error: npm is required but not found in PATH." >&2
  exit 1
fi

if [[ ! -f "$REPO_ROOT/package.json" ]]; then
  echo "Error: package.json not found at $REPO_ROOT" >&2
  exit 1
fi

if [[ ! -f "$CLI_PATH" ]]; then
  echo "Error: CLI not found at $CLI_PATH" >&2
  exit 1
fi

mkdir -p "$TARGET_DIR"

if [[ -e "$TARGET" ]]; then
  if ! grep -qF "$MARKER" "$TARGET" 2>/dev/null; then
    if [[ "$FORCE" -ne 1 ]]; then
      echo "Error: $TARGET already exists and was not created by this installer." >&2
      echo "Re-run with --force to replace it, or remove the file manually." >&2
      exit 1
    fi
    echo "Warning: replacing existing $TARGET (--force)." >&2
  fi
fi

# 临时文件必须与目标同处一个文件系统，否则 mv 会退化为「复制 + 删除」，失去原子性
TMP="$(mktemp "$TARGET_DIR/.openclaw-usage.XXXXXX")"
cleanup() { rm -f "$TMP"; }
trap cleanup EXIT

cat > "$TMP" <<EOF
#!/usr/bin/env bash
$MARKER
# Generated by OpenClawUsage scripts/install-local-launcher.sh
# Do not edit; re-run the installer after moving the repository.
exec node $(printf '%q' "$CLI_PATH") "\$@"
EOF

chmod 755 "$TMP"
mv -f "$TMP" "$TARGET"
trap - EXIT

echo "Installed: $TARGET"
echo "Repository: $REPO_ROOT"

case ":$PATH:" in
  *":$TARGET_DIR:"*)
    echo "PATH already includes $TARGET_DIR"
    ;;
  *)
    cat <<EOF

Note: $TARGET_DIR is not in your PATH.
Add one of the following to your shell profile, then restart the shell:

  export PATH="\$HOME/bin:\$PATH"

Or for zsh (~/.zshrc):

  export PATH="\$HOME/bin:\$PATH"
EOF
    ;;
esac

echo
echo "Next steps:"
echo "  openclaw-usage build"
echo "  openclaw-usage start"
echo "  openclaw-usage stop"
